// Import mongodb
import * as mongodb from "mongodb"

// Export the employee interface
export interface Employee {
    name: string
    position: string
    level: "junior" | "mid" | "senior"
    _id?: mongodb.ObjectId // The ? makes the field optional and it's generated by the mongodb and doesn't need to be specified when creating an employee but with auto populate
}